[[redirects]]
  from = "/api/messages"
  to = "/.netlify/functions/messages"
  status = 200

[build]
  environment = { NODE_VERSION = "16" }

[build.processing]
  skip_processing = true

[template.environment]
  COURIER_AUTH_TOKEN = "Courier auth token (required)"
  MSTEAMS_APP_ID = "Microsoft Teams App ID (required)"
  MSTEAMS_APP_PASSWORD = "Microsoft Teams App Password (required)"