[[redirects]]
  from = "/api/messages"
  to = "/api/internal/messages"
  status = 200

[functions]
  directory = "netlify/functions"

[template.environment]
  COURIER_AUTH_TOKEN = "Courier auth token (required)"
  MSTEAMS_APP_ID = "Microsoft Teams App ID (required)"
  MSTEAMS_APP_PASSWORD = "Microsoft Teams App Password (required)"